apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:eQM3HhU8PfPpyHAwu3scmFcDPqY=,iv:M9fGY71GAea+ir6bIjGVLpZI5zoscARTQ+iZLfw9hUs=,tag:OXEFlrAb7uU4Ax0ziHekmw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1sxlt505j5xlzvq8puwfh6r90qf3kgtdhnry7agycr6c4d98sds9q3p9nu8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTG9CV0pRMkkxWVlFVFRM
        NzVwbGoyc2loOTN4aXhRY25QaVRTaDZheEFBCmxmRDRmUUsrRDhEN1BCVS91Um1X
        aUNiMFk0YkVsL0tJaUZ6d3RFek5DWlkKLS0tIHRDSVhTNlFQOFV6MU14dGNsTlJ4
        N0pVQkx3a2lwZ2draHNadlVqeDZmSlkKGyqFtAJuuqEHkaLoxgrsMjBeZMXoiNcD
        sWwFZ9XyaSXxR1FKQT4BxSIUi49aHuz2aB4fD3smNMao4tz3qh+zPA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-10T05:25:48Z"
  mac: ENC[AES256_GCM,data:S5xP3izpvLppZnbS/r815wn+6Gg8ZkPRiVawUJsemGaR8e1k5Va2dfJXxxZ1K0e4gF6W+IS5frw9QGivf322MY5ifTshdeZ/Bay0V9GsBRSlo6OSxmbo7sqx8tJOYduMEJQEeua2p4Cxuxp8iCBatvPgt1GjDVgpP6xnFOhHgnk=,iv:PUhbIZVn7CpCjsEsF2V6d2OcHofMYGE97OdCLHgijyg=,tag:GqbvVrDRvVsShasjRs8frg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
